### PR TITLE
Fix setting torch's tensor default to float (was double)

### LINKED ISSUE #1134: Torch data augmentation doesn't work with latest build
@TimZaman looks like some API changed in `image`. Can you look into it? It's breaking our Travis builds:

https://travis-ci.org/NVIDIA/DIGITS/jobs/164697648
```
digits.webapp: ERROR: Train Torch Model: ...e/travis/torch/install/share/lua/5.1/threads/threads.lua:183: [thread 3 callback] /home/travis/torch/install/share/lua/5.1/image/init.lua:966: bad argument #3 to 'warp' (torch.FloatTensor expected, got torch.DoubleTensor)
digits.webapp: WARNING: Train Torch Model unrecognized output: stack traceback:
digits.webapp: WARNING: Train Torch Model unrecognized output: [C]: in function 'warp'
digits.webapp: WARNING: Train Torch Model unrecognized output: /home/travis/torch/install/share/lua/5.1/image/init.lua:966: in function 'warp'
digits.webapp: WARNING: Train Torch Model unrecognized output: ...e/travis/build/NVIDIA/DIGITS/digits/tools/torch/data.lua:239: in function 'PreProcess'
digits.webapp: WARNING: Train Torch Model unrecognized output: ...e/travis/build/NVIDIA/DIGITS/digits/tools/torch/data.lua:657: in function 'nextBatch'
digits.webapp: WARNING: Train Torch Model unrecognized output: ...e/travis/build/NVIDIA/DIGITS/digits/tools/torch/data.lua:793: in function <...e/travis/build/NVIDIA/DIGITS/digits/tools/torch/data.lua:787>
digits.webapp: WARNING: Train Torch Model unrecognized output: [C]: in function 'xpcall'
digits.webapp: WARNING: Train Torch Model unrecognized output: ...e/travis/torch/install/share/lua/5.1/threads/threads.lua:234: in function 'callback'
digits.webapp: WARNING: Train Torch Model unrecognized output: /home/travis/torch/install/share/lua/5.1/threads/queue.lua:65: in function </home/travis/torch/install/share/lua/5.1/threads/queue.lua:41>
digits.webapp: WARNING: Train Torch Model unrecognized output: [C]: in function 'pcall'
digits.webapp: WARNING: Train Torch Model unrecognized output: /home/travis/torch/install/share/lua/5.1/threads/queue.lua:40: in function 'dojob'
digits.webapp: WARNING: Train Torch Model unrecognized output: [string "  local Queue = require 'threads.queue'..."]:15: in main chunk
digits.webapp: WARNING: Train Torch Model unrecognized output: DIGITS Lua Error
digits.webapp: WARNING: Train Torch Model unrecognized output: stack traceback:
digits.webapp: WARNING: Train Torch Model unrecognized output: [C]: in function 'error'
digits.webapp: WARNING: Train Torch Model unrecognized output: ...e/travis/torch/install/share/lua/5.1/threads/threads.lua:183: in function 'dojob'
digits.webapp: WARNING: Train Torch Model unrecognized output: ...e/travis/build/NVIDIA/DIGITS/digits/tools/torch/data.lua:816: in function 'waitNext'
digits.webapp: WARNING: Train Torch Model unrecognized output: ...e/travis/build/NVIDIA/DIGITS/digits/tools/torch/main.lua:755: in function 'Train'
digits.webapp: WARNING: Train Torch Model unrecognized output: ...e/travis/build/NVIDIA/DIGITS/digits/tools/torch/main.lua:848: in main chunk
digits.webapp: WARNING: Train Torch Model unrecognized output: [C]: in function 'dofile'
digits.webapp: WARNING: Train Torch Model unrecognized output: ...ravis/build/NVIDIA/DIGITS/digits/tools/torch/wrapper.lua:25: in function <...ravis/build/NVIDIA/DIGITS/digits/tools/torch/wrapper.lua:25>
digits.webapp: WARNING: Train Torch Model unrecognized output: [C]: in function 'xpcall'
digits.webapp: WARNING: Train Torch Model unrecognized output: ...ravis/build/NVIDIA/DIGITS/digits/tools/torch/wrapper.lua:25: in main chunk
digits.webapp: WARNING: Train Torch Model unrecognized output: [C]: in function 'dofile'
digits.webapp: WARNING: Train Torch Model unrecognized output: ...avis/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
digits.webapp: WARNING: Train Torch Model unrecognized output: [C]: at 0x00406670
digits.webapp: ERROR: Train Torch Model task failed with error code 1
```

### PR DESCRIPTION
**Pull request by TimZaman**
Probably fixes #1134. Was due to an (unnesecary imo) breaking change in https://github.com/torch/image/pull/189 .

### CODE REVIEW

**Comment by TimZaman** [comment]
cc @gheinrich . I'm now mostly checking what Travis thinks about this PR. It seems we're not using double tensors anywhere ever though.

**Comment by chsasank** [comment]
Hi, 

The error was
```
digits.webapp: ERROR: Train Torch Model: ...e/travis/torch/install/share/lua/5.1/threads/threads.lua:183: [thread 3 callback] /home/travis/torch/install/share/lua/5.1/image/init.lua:966: bad argument #3 to 'warp' (torch.FloatTensor expected, got torch.DoubleTensor)
```

Very similar error(https://github.com/torch/image/issues/187) was fixed by https://github.com/torch/image/pull/189 

You may take cues from this PR and fix `wrap` in torch/image

**Comment by TimZaman** [comment]
Hmm it is similar but no, torch/image#189 introduced it.

**Comment by TimZaman** [comment]
Okay, tracked it down. The bug was introduced by torch/image#189 indeed. It tried to solve another bug but introduced another, and that affected us. The fix is a one-liner in torch, fixing it while supporting the previous and current torch/image versions in torch is more painful. Before and after the `warp()` statement we could switch between 
`torch.setdefaulttensortype('torch.FloatTensor')`
and then back to
`torch.setdefaulttensortype('torch.DoubleTensor')`
afterwards. But I think we should be able to set the torch.FloatTensor as default globally in any case.

**Comment by lukeyeager** [comment]
Since the bug was fixed in https://github.com/torch/image/pull/189, let's push an update to `torch/distro` instead of putting in a temporary fix.

@TimZaman agreed?

**Comment by TimZaman** [comment]
Aye captain

**Pull request closed without merging**
