### PR TITLE
Fix error in score reporting of "Infer Many Images" function

### PR DESCRIPTION
**Pull request by descampsa**
Fix https://github.com/NVIDIA/DIGITS/issues/255

### CODE REVIEW

**Comment by lukeyeager** [comment]
@descampsa, #255 reports a problem with `infer_many()` (for `GenericModelJobs`), but this is a fix for `classify_many()` (for `ClassificationModelJobs`). There's no problem with `classify_many()` as far as I know.

Please explain.

**Comment by descampsa** [comment]
Humm, sorry about the poorly described patch and the confusion.
I noticed a bug in `classify_many`, and the symptoms described in https://github.com/NVIDIA/DIGITS/issues/255 were so close to mine that i thought it was the same issue.

Here is the bug i noticed : the scores for the first chunk of images (images 0 to 15 in my case) returned by classify_many are incorrect, and they are the same as the next chunk (image 16 to 31). 
This is due to the way the score vector is accumulated : the first iteration does a swallow copy of the result, and second iteration write on the same vector and overwrite first results. 
Next iteration are fine because they use vstack.
The patch fix the issue for me by using `copy.deepcopy` at first iteration.

As for https://github.com/NVIDIA/DIGITS/issues/255, i am not sure anymore if it is related, but it seems that a similar logic is used in `infer_many`, so maybe a similar patch (at line [1258](https://github.com/descampsa/DIGITS/blob/f4a636d4bf8241abe26754cac3c993954ebc5fd1/digits/model/tasks/caffe_train.py#L1258) ) is needed.

**Comment by lukeyeager** [comment]
Thanks for the explanation. I can reproduce the bug on my machine exactly as you described - thanks for the bugfix! As you guessed, this is broken for `infer_many` as well, can you add the same fix at line 1258?

Also, I'll need you to send us a signed CLA before I can accept your contribution.

> Send a signed copy of the Contributor License Agreement (CLA) to digits@nvidia.com.

> \- https://github.com/NVIDIA/DIGITS/blob/master/CONTRIBUTING.md#pull-requests

**Comment by descampsa** [comment]
If i have to sign an agreement, i prefer that you consider this as an issue report, and fix it yourself, especially for such a straightforward fix.
Thanks.

**Pull request closed without merging**
