### PR TITLE
Add MacOS instructions

### PR DESCRIPTION
**Pull request by trivedigaurav**

### CODE REVIEW

**Comment by lukeyeager** [comment]
Oh, I didn't realize you could just install gunicorn with pip. Duh. I'll move that into `requirements.txt` in an upcoming commit.

**Comment by trivedigaurav** [comment]
:+1 Yes, that would be neater.

**Comment by trivedigaurav** [comment]
I have updated the PR to include gunicorn in requirements.txt.

**Comment by lukeyeager** [comment]
Thanks for contributing!

**Pull request merged**
