### PR TITLE
Bugfix in case of missing localStorage.model_fields (#1255)

### PR DESCRIPTION
**Pull request by jmancewicz**
Bugfix for the case where $localStorage.model_fields has not been defined.

### CODE REVIEW

**Comment by lukeyeager** [comment]
(fixes #1255)

**Comment by jmancewicz** [comment]
Works correctly after issuing `localStorage.clear();` in firefox console and reloading the page

**Comment by lukeyeager** [comment]
Please wait for TravisCI to pass before merging.

**Comment by jmancewicz** [comment]
Sure thing.

**Pull request merged**
