### PR TITLE
Fix parsing of infinite loss in Torch

### PR DESCRIPTION
**Pull request by gheinrich**
Lua uses 'inf' to represent infinite numbers. Additionally Torch may use
'nan' in its representation of infinite values in Tensors.

We must catch both cases in the parsing of training and validation
losses.

Add test to verify functionality.

### CODE REVIEW

**Comment by gheinrich** [comment]
Note that I was unable to get the new test to pass for Caffe on the Travis machine (it did always pass on my machine). Maybe that has something to do with CuDNN support (which I suppose is not compiled in on the Travis machine)?

**Comment by lukeyeager** [comment]
> Note that I was unable to get the new test to pass for Caffe on the Travis machine

Looks like they passed to me ... Did you restart it?

> CuDNN support (which I suppose is not compiled in on the Travis machine)?

That's true. Travis builds caffe without CUDA or cuDNN.
https://github.com/NVIDIA/DIGITS/blob/v2.2.1/scripts/travis/install-caffe.sh#L30-L31

**Comment by lukeyeager** [comment]
Tests pass on my machine and they seem to pass on Travis despite your comment above. Merging.

**Comment by gheinrich** [comment]
I forgot to mention I [skip](https://github.com/gheinrich/DIGITS/blob/58e07e883675d9608215daf1f019db78fe5a20fb/digits/model/images/generic/test_views.py#L359) the test in Caffe case.

**Pull request merged**
