### PR TITLE
Torch multi-threaded data loader

### PR DESCRIPTION
**Pull request by gheinrich**
Using MNIST (45k training samples, 15k validation samples) and LeNet (20 epochs):
original: 118s
new: 91s

Using CIFAR10 (images upscaled to 256x256):
Alexnet (2 epochs) original: 948s
Alexnet (2 epochs) new: 869s
GoogLenet (2 epochs) original: 5280s
GoogLenet (2 epochs) new: 5100s

### CODE REVIEW

**Comment by gheinrich** [comment]
Not for merging now - will conflict with #321. I will rebase when #321 is merged.

**Comment by lukeyeager** [comment]
Re-filed at https://github.com/NVIDIA/DIGITS/pull/388.

**Comment by gheinrich** [comment]
Yes, sorry I accidentally pushed the tip of NVIDIA:master on my branch gheinrich:dev/multi-threaded-test and this automatically closed this PR (presumably because Github noticed I wasn't pushing any new change). When I pushed my commit again on gheinrich:dev/multi-threaded-test  this created #390 automatically too...

**Comment by lukeyeager** [comment]
Haha really? C'mon GitHub.

**Pull request closed without merging**
