### PR TITLE
Use in-place multiplication.

### PR DESCRIPTION
**Pull request by Liuftvafas**

### CODE REVIEW

**Comment by lukeyeager** [comment]
Is this a bug or an enhancement? Assigning Greg to review.

**Comment by gheinrich** [comment]
It's an enhancement (allows doing the multiplication by 255 without allocating a new tensor). I am adding the `enhancement` label.

**Comment by gheinrich** [comment]
Looks good to me. Waiting for [CLA](https://github.com/NVIDIA/DIGITS/blob/master/CONTRIBUTING.md#pull-requests) notification.

**Comment by lukeyeager** [comment]
CLA received. Thanks @Liuftvafas!

**Pull request merged**
