### PR TITLE
Explore generic datasets

### PR DESCRIPTION
**Pull request by gheinrich**
Add button to explore **encoded** LMDBs

### CODE REVIEW

**Comment by lukeyeager** [comment]
Neat!

**Comment by lukeyeager** [comment]
@gheinrich I merged this a little prematurely. I reverted it manually and we can look at adding it after tagging the 4.0 RC. Sorry for the inconvenience!

**Comment by gheinrich** [comment]
No problem. Out of curiosity, did you revert because you spotted an issue?

**Comment by lukeyeager** [comment]
The importing of `caffe_pb2` looked fishy. I've broken the test suite before when I try to run specific tests. You might be fine in this case, but I'd rather not merge something that touches this much code right at RC time.

**Pull request merged**
