### PR TITLE
Fix backend gtk3 error NVIDIA/DIGITS#187 NVIDIA/DIGITS#78

### PR DESCRIPTION
**Pull request by nszceta**

### CODE REVIEW

**Comment by lukeyeager** [comment]
@gheinrich, it looks like you first suggested this fix at https://github.com/NVIDIA/DIGITS/issues/187#issuecomment-126611403. Can you explain where you got this from and why it works? I'd rather not add another library dependency if this can be solved in another way.

**Comment by gheinrich** [comment]
My vague understanding is that matplotlib can operate with a number of rendering backends. There are 'interactive' backends which allow the user to interact with the backend (I suppose for zooming, panning, etc.). There are also non-interactive backends that e.g. only allow the rendering to be saved to files. By default matplotlib uses Gtk3, which is an interactive backend and needs a working display. Matplotlib has an API to switch the rendering backend. Doing `matplotlib.use('Agg')` selects a non-interactive backend, as suggested on BVLC/caffe#861.

We are using skimage which relies on matplotlib and I think the 'fix' is to make sure we switch the matplotlib backend before using skimage. In my understanding we already have a dependency on matplotlib through skimage so I think the change does not add a new dependency.

**Comment by lukeyeager** [comment]
Thanks for the explanation! Should we make that an explicit requirement in `requirements.txt` or is this a caffe-specific thing?

**Comment by nszceta** [comment]
It is a dependency of skimage. Nothing needed.

--
Adam Gradzki

**Comment by lukeyeager** [comment]
Right, but we don't explicitly require either `scikit-image` or `matplotlib` in [requirements.txt](https://github.com/NVIDIA/DIGITS/blob/v2.1.0/requirements.txt) - those are coming from [Caffe's list](https://github.com/NVIDIA/caffe/blob/v0.13.1/python/requirements.txt). All libraries used in DIGITS ought to be listed in the DIGITS requirements, even if they're also listed in the pycaffe requirements.

@nszceta, can you add this line to `requirements.txt` in this pull request please?

    matplotlib>=1.3.1

Also, I'll need you to send us a signed CLA before I can accept your contribution. Sorry for the inconvenience.
> Send a signed copy of the Contributor License Agreement (CLA) to digits@nvidia.com.

> \- https://github.com/NVIDIA/DIGITS/blob/master/CONTRIBUTING.md#pull-requests

**Comment by nszceta** [comment]
I can not sign the CLA at this time. Please close the pull request.

--
Adam Gradzki

**Pull request closed without merging**
