### PR TITLE
removed buggy has_labels from pretrained models

### PR DESCRIPTION
**Pull request by Lucaszw**

### CODE REVIEW

**Comment by lukeyeager** [comment]
Have you tested this yet?

    "global name 'os' is not defined"

**Comment by Lucaszw** [comment]
@lukeyeager Sorry my bad! Should be fixed now

**Comment by lukeyeager** [comment]
Ok, this seems to work now. I'll merge once Travis passes.

**Comment by lukeyeager** [comment]
The Travis failures seem to be caused by some change in the Torch tree - so they're unrelated.

**Pull request merged**
