### PR TITLE
patch for running on windows ENV.

### PR DESCRIPTION
**Pull request by bygreencn**
Patch for windows ENV.

### CODE REVIEW

**Comment by lukeyeager** [comment]
@IsaacYangSLA is making changes to this file at https://github.com/NVIDIA/DIGITS/pull/769. I think it may address your issues? Also, your changes break the TravisCI build.

**Comment by IsaacYangSLA** [comment]
Some codes seem duplicate.  @bygreencn , can you re-organize the codes?

**Comment by lukeyeager** [comment]
Should be fixed by https://github.com/NVIDIA/DIGITS/pull/769.

**Comment by bygreencn** [comment]
@IsaacYangSLA Sorry, i lost your messaage, now i have update the code to be compatible with window.
@lukeyeager #769 still need the update with this commit.

**Comment by lukeyeager** [comment]
Can you explain what your patch is supposed to do? Nowhere in these comments or your commit message do I see anything explaining what issue you're solving. Please explain what is missing from #769 that you still need addressed.

**Pull request closed without merging**
