### PR TITLE
More robust Torch image classification test

### PR DESCRIPTION
**Pull request by gheinrich**
- using a color model of LeNet to more accurate discrimination
of color images.
- add more combinations of training parameters (DB backend and shuffle).
- test correct classification of all categories

### CODE REVIEW

**Comment by lukeyeager** [comment]
This is in reference to #346, correct?

**Comment by gheinrich** [comment]
Yes this should address some test failures I've seen in the "LeNet" tests. 
Note the separate copy of LeNet definition for color images. I am planning to merge the grayscale and color definitions later when I have implemented the option to pass tensor dimensions to the models.

**Comment by lukeyeager** [comment]
LGTM.

**Comment by lukeyeager** [comment]
> Note the separate copy of LeNet definition for color images. I am planning to merge the grayscale and color definitions later when I have implemented the option to pass tensor dimensions to the models.

Sounds good.

**Pull request merged**
