### PR TITLE
Add a HOWTO example for Python layers

### PR DESCRIPTION
**Pull request by lukeyeager**
*Chipping away at #401*

NOTE: you need the fix from https://github.com/NVIDIA/DIGITS/pull/444 before you can test this.

### CODE REVIEW

**Comment by lukeyeager** [comment]
@jmancewicz, @gheinrich - can one of you guys try this out? It'll be a good way to test #444 as well.

**Comment by jmancewicz** [comment]
Worked very well.  I like the extra credit section.

**Comment by gheinrich** [comment]
Worked for me too (a note to highlight the fact that Python layers must be enabled when compiling Caffe could be useful). Thanks.

**Comment by lukeyeager** [comment]
> (a note to highlight the fact that Python layers must be enabled when compiling Caffe could be useful)

Done. I also addressed Joe's whitespace suggestion. Thanks for taking a look!

**Pull request merged**
