### PR TITLE
Torch model fine-tuning

### PR DESCRIPTION
**Pull request by gheinrich**

### CODE REVIEW

**Comment by lukeyeager** [comment]
If I try to use a snapshot from a previous model (and don't customize the network), I get the error below.

I assume this is because the last layer isn't renamed? That's easy to do in Caffe, but I suspect it's not easy with Torch, right?
```
2016-01-13 13:11:00 [INFO ] Loading mean tensor from /raid/jobs/dev/20160113-130553-886a/mean.jpg file
2016-01-13 13:11:00 [INFO ] Loading label definitions from /raid/jobs/dev/20160113-130553-886a/labels.txt file
2016-01-13 13:11:00 [INFO ] found 2 categories
2016-01-13 13:11:00 [INFO ] creating data readers
2016-01-13 13:11:00 [INFO ] opening LMDB database: /raid/jobs/dev/20160113-130553-886a/train_db
2016-01-13 13:11:00 [INFO ] Image channels are 1, Image width is 28 and Image height is 28
2016-01-13 13:11:00 [INFO ] opening LMDB database: /raid/jobs/dev/20160113-130553-886a/train_db
2016-01-13 13:11:00 [INFO ] Image channels are 1, Image width is 28 and Image height is 28
2016-01-13 13:11:00 [INFO ] opening LMDB database: /raid/jobs/dev/20160113-130553-886a/train_db
2016-01-13 13:11:00 [INFO ] Image channels are 1, Image width is 28 and Image height is 28
2016-01-13 13:11:00 [INFO ] opening LMDB database: /raid/jobs/dev/20160113-130553-886a/train_db
2016-01-13 13:11:00 [INFO ] Image channels are 1, Image width is 28 and Image height is 28
2016-01-13 13:11:00 [INFO ] found 50 images in train db/raid/jobs/dev/20160113-130553-886a/train_db
2016-01-13 13:11:01 [INFO ] opening LMDB database: /raid/jobs/dev/20160113-130553-886a/val_db
2016-01-13 13:11:01 [INFO ] Image channels are 1, Image width is 28 and Image height is 28
2016-01-13 13:11:01 [INFO ] opening LMDB database: /raid/jobs/dev/20160113-130553-886a/val_db
2016-01-13 13:11:01 [INFO ] Image channels are 1, Image width is 28 and Image height is 28
2016-01-13 13:11:01 [INFO ] opening LMDB database: /raid/jobs/dev/20160113-130553-886a/val_db
2016-01-13 13:11:01 [INFO ] Image channels are 1, Image width is 28 and Image height is 28
2016-01-13 13:11:01 [INFO ] opening LMDB database: /raid/jobs/dev/20160113-130553-886a/val_db
2016-01-13 13:11:01 [INFO ] Image channels are 1, Image width is 28 and Image height is 28
2016-01-13 13:11:01 [INFO ] found 150 images in train db/raid/jobs/dev/20160113-130553-886a/val_db
2016-01-13 13:11:01 [INFO ] Loading network definition from /raid/jobs/dev/20160113-131059-4593/model
Using CuDNN backend
2016-01-13 13:11:01 [INFO ] Train batch size is 64 and validation batch size is 16
2016-01-13 13:11:01 [INFO ] Network definition:
nn.Sequential {
[input -> (1) -> (2) -> (3) -> (4) -> (5) -> (6) -> (7) -> (8) -> (9) -> (10) -> output]
(1): nn.MulConstant
(2): cudnn.SpatialConvolution(1 -> 20, 5x5)
(3): cudnn.SpatialMaxPooling(2,2,2,2)
(4): cudnn.SpatialConvolution(20 -> 50, 5x5)
(5): cudnn.SpatialMaxPooling(2,2,2,2)
(6): nn.View
(7): nn.Linear(800 -> 500)
(8): cudnn.ReLU
(9): nn.Linear(500 -> 2)
(10): nn.LogSoftMax
}
2016-01-13 13:11:01 [INFO ] Network definition ends
2016-01-13 13:11:01 [INFO ] Loading weights from pretrained model - /raid/jobs/dev/20160113-130752-07aa/snapshot_30_Weights.t7
2016-01-13 13:11:01 [FAIL] /home/lyeager/digits/tools/torch/main.lua:374: bad argument #1 to 'copy' (sizes do not match at /home/bfomitchev/git/d4/extra/cutorch/lib/THC/THCTensorCopy.c:92)
DIGITS Lua Error
stack traceback:
[C]: in function 'copy'
/home/lyeager/digits/tools/torch/main.lua:374: in main chunk
[C]: in function 'dofile'
/home/lyeager/digits/tools/torch/wrapper.lua:25: in function </home/lyeager/digits/tools/torch/wrapper.lua:25>
[C]: in function 'xpcall'
/home/lyeager/digits/tools/torch/wrapper.lua:25: in main chunk
[C]: in function 'dofile'
/usr/local/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
[C]: at 0x00406670
```

**Comment by gheinrich** [comment]
Indeed, Torch layers are not named therefore in this implementation of fine tuning you need to provide the exact structure of the original model so that weights can be copied verbatim. Then in your `fineTuneHook` you can alter the model to solve a slightly different task. I should probably add a few lines to the documentation to make this more explicit.

If you use the standard LeNet model there is code to dynamically adjust the number of outputs in the last layer based on how many classes you have in your dataset. Therefore if you originally train a model on a 10-class problem then wish to fine-tune it to solve a 2-class problem, you'll need to hard code the number of outputs to 10. In the `fineTuneHook` you can either replace that last layer with a linear layer with two outputs, or you can just add a 10->2 linear layer on top.

**Comment by lukeyeager** [comment]
I see. So that's why #498 is pretty much impossible with Torch.

**Comment by lukeyeager** [comment]
Can we add some HTML and/or Javascript to disallow it, then? If someone has a pretrained model selected on the `Previous` tab for Torch, then something should let them know it's not going to work. At the bare minimum, let's update the [Torch warning](https://github.com/NVIDIA/DIGITS/blob/5fddcecf22/digits/templates/models/images/classification/new.html#L411-L417) to be more accurate and informative.

**Comment by gheinrich** [comment]
Thanks, I have added a note in the Torch warning to say that fine-tuning from multiple pretrained models is not supported in Torch.

I have also added a note in the Getting Started for Torch to mention the fact that the model returned in the user-defined description must be exactly the same as the original model to fine-tune.

**Pull request merged**
