### PR TITLE
Expose common dataset interface

### PR DESCRIPTION
**Pull request by gheinrich**
This will allow to create new types of datasets without making changes in other parts of DIGITS.

Ultimately, class relationships may look like:
data-classes

### CODE REVIEW

**Comment by lukeyeager** [comment]
I like the direction! Looks like this is a work-in-progress?

Looks like you removed `json_dict` from `DatasetJob` and didn't add it to `GenericImageDatasetJob`.

**Comment by gheinrich** [comment]
I didn't base this commit on the latest version of master because of the parameter-sweep issue. Other than that, I feel this could be good to merge if it passes the test of your most accurate review filter :-)

I didn't add `json_dict` to `GenericImageDatasetJob` because the version I removed from `DatasetJob` was classification specific (i.e. it had no effect on the generic path).

**Comment by gheinrich** [comment]
Rebased on tip of master branch.

**Comment by lukeyeager** [comment]
I think this is working. I ran into some Torch errors, but I don't think they were related.

**Pull request merged**
