### PR TITLE
Fix typos in docs and examples

### PR DESCRIPTION
**Pull request by dongjoon-hyun**

### CODE REVIEW

**Comment by gheinrich** [comment]
Thanks @dongjoon-hyun. These all look good to me!

**Comment by dongjoon-hyun** [comment]
Thank you, @gheinrich and @lukeyeager . 
I sent my CLA for this PR a few minutes ago.

**Comment by lukeyeager** [comment]
Thanks @dongjoon-hyun!

**Comment by dongjoon-hyun** [comment]
Thank you again! :)

**Pull request merged**
