### PR TITLE
Update inference.py (bug fix)

### PR DESCRIPTION
**Pull request by patricio-astudillo**
The error message contains a reference to self, which is not present since it is outside a class. I propose to remove the self from the error message.

### CODE REVIEW

**Comment by gheinrich** [comment]
That looks good to me thanks for fixing this!

**Comment by gheinrich** [comment]
@patricio-astudillo do you mind filling the CLA (see [instructions](https://github.com/NVIDIA/DIGITS/blob/61427811a2b7b23cc2004efe8ebc6b7ded200681/.github/CONTRIBUTING.md#pull-requests)). Thanks!

**Comment by patricio-astudillo** [comment]
Ok, Ive sent the CLA to digits@nvidia.com
Is there anything else I need to do from my side?

**Comment by lukeyeager** [comment]
Thanks for the fix!

**Pull request merged**
