### PR TITLE
Siamese network tutorial for Torch

### PR DESCRIPTION
**Pull request by gheinrich**

### CODE REVIEW

**Comment by gheinrich** [comment]
Depends on #483 and #485

**Comment by lukeyeager** [comment]
Very cool tutorial! I especially like the images at the end. However, I'm running into what looks like a Torch version issue.

When I use Torch from a deb installer, I get this error:
```
2015-12-28 10:03:52 [FAIL] /usr/local/share/lua/5.1/nn/Narrow.lua:14: bad argument #3 to 'narrow' (out of range at /home/bfomitchev/git/d4/extra/cutorch/lib/THC/THCTensor.c:367)
DIGITS Lua Error
stack traceback:
[C]: in function 'narrow'
/usr/local/share/lua/5.1/nn/Narrow.lua:14: in function 'updateOutput'
/usr/local/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
/home/lyeager/digits/tools/torch/main.lua:622: in function 'Validation'
/home/lyeager/digits/tools/torch/main.lua:779: in main chunk
[C]: in function 'dofile'
/home/lyeager/digits/tools/torch/wrapper.lua:25: in function </home/lyeager/digits/tools/torch/wrapper.lua:25>
[C]: in function 'xpcall'
/home/lyeager/digits/tools/torch/wrapper.lua:25: in main chunk
[C]: in function 'dofile'
/usr/local/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
[C]: at 0x00406670
```
@borisfom why is your home directory hard-coded into the Torch installation!?

When I use my local torch installation, I get the same error:
```
2015-12-28 10:06:25 [FAIL] /home/lyeager/torch/install/share/lua/5.1/nn/Narrow.lua:14: bad argument #3 to 'narrow' (out of range at /home/lyeager/torch/extra/cutorch/lib/THC/THCTensor.c:367)
DIGITS Lua Error
stack traceback:
[C]: in function 'narrow'
/home/lyeager/torch/install/share/lua/5.1/nn/Narrow.lua:14: in function 'updateOutput'
/home/lyeager/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
/home/lyeager/digits/tools/torch/main.lua:622: in function 'Validation'
/home/lyeager/digits/tools/torch/main.lua:779: in main chunk
[C]: in function 'dofile'
/home/lyeager/digits/tools/torch/wrapper.lua:25: in function </home/lyeager/digits/tools/torch/wrapper.lua:25>
[C]: in function 'xpcall'
/home/lyeager/digits/tools/torch/wrapper.lua:25: in main chunk
[C]: in function 'dofile'
...ager/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
[C]: at 0x00406670
```

**Comment by gheinrich** [comment]
Hi Luke and sorry for the late feedback. Do you have three channels in your input images? You should if you're using `create_db.py` to create your LMDB database.

**Comment by lukeyeager** [comment]
I'm not sure what I was doing before. It works for me now.

There's a merge conflict from #510 before we can merge.

By the way, that `create_db.py` script is SUPER slow for me. It wasn't responding when I gave it `-c 100000`, so I took it down to `-c 100` and it still took 199 seconds to finish. It's all disk IO, the CPU is hardly used at all. Are you seeing the same?

**Comment by gheinrich** [comment]
Thanks Luke, I have rebased this PR on the tip of the master branch.

Regarding the DB creation slowliness I realized that the script was flushing data to the filesystem after each sample. Creating a database of 100,000 samples was taking about 15 minutes on my SSD drive but slower filesystems (network?) might have been even slower. On #519 I have implemented batch writing. This speeds DB creation up considerably.

**Pull request merged**
