### PR TITLE
Fix batch accumulation

### LINKED ISSUE #1240: Incorrect iteration_to_epoch calculation with batch_accumulation
Hello,
I'm not a 100% sure, but I think the calculation of iteration_to_epoch is incorrect when using batch_accumulation. I guess this is due to the calculation of solver.max_iter since it doesn't take batch_accumulation into account.

### PR DESCRIPTION
**Pull request by lukeyeager**
*Fix #1240*

### CODE REVIEW

**Comment by kostinalexey** [comment]
You need to modify following lines to fix test and display parameters for caffe

542-544, 
-            solver.test_iter.append(int(math.ceil(float(self.dataset.get_entry_count(constants.VAL_DB)) / val_data_layer.data_param.batch_size)))
+            solver.test_iter.append(int(math.ceil(float(self.dataset.get_entry_count(constants.VAL_DB)) / (val_data_layer.data_param.batch_size * self.batch_accumulation))))
 
603, 
-                int(math.ceil(5000.0 / train_data_layer.data_param.batch_size))
+                int(math.ceil(5000.0 / (train_data_layer.data_param.batch_size * self.batch_accumulation)))

772-773
-            solver.test_iter.append(int(math.ceil(float(self.dataset.get_entry_count(constants.VAL_DB)) / val_image_data_layer.data_param.batch_size)))
+            solver.test_iter.append(int(math.ceil(float(self.dataset.get_entry_count(constants.VAL_DB)) / (val_image_data_layer.data_param.batch_size * self.batch_accumulation))))

828
-                int(math.ceil(5000.0 / train_image_data_layer.data_param.batch_size))
+                int(math.ceil(5000.0 / (train_image_data_layer.data_param.batch_size * self.batch_accumulation)))

**Comment by lukeyeager** [comment]
@kostinalexey as far as I can tell, batch accumulation has no effect during the TEST phase. Do you have proof to the contrary?

You're right about the display bug though - thanks! Let me fix that...

**Comment by kostinalexey** [comment]
You are right, test phase is not effected by batch_accumulation. My mistake.

**Comment by lukeyeager** [comment]
No problem at all - thanks for double-checking my work!

**Pull request merged**
