### PR TITLE
Let digits can create rec database.

### PR DESCRIPTION
**Pull request by SevenGong**
Let digits can create rec database.

### CODE REVIEW

**Comment by TimZaman** [comment]
Duplicate of https://github.com/NVIDIA/DIGITS/pull/1001?

**Comment by SevenGong** [comment]
@TimZaman  Hi,this PR is modified a little, but it failed again.It shows some errors about test. I am not obvious how to solve.

**Comment by SevenGong** [comment]
@TimZaman Now I have modified this indent problem. And now I trace my PR and notice the problem is at https://github.com/NVIDIA/DIGITS/blob/v4.0.0/digits/task.py#L208 . My code walk to this place and stop here, and it cannot walk next step to run the digits/tools/create_db.py. I was wondering. Do you know why? 
As for any other codes of my RP, it seems to be right, no errors.

**Comment by lukeyeager** [comment]
@SevenGong if you want to continue this discussion, you can make comments on your original pull request. Please don't create duplicate pull requests.

However, as explained at https://github.com/NVIDIA/DIGITS/pull/1001#issuecomment-244202338, I think you're underestimating the work it would take to add mxnet support to DIGITS.

**Comment by SevenGong** [comment]
@lukeyeager Thank you very much. I am very interested in your digits,but I am newly graduated student, and need to learn more.But I will work hard. Always thanks for your guidance.

**Pull request closed without merging**
