### PR TITLE
Upgrade caffe_train_task.network object type

### PR DESCRIPTION
**Pull request by lukeyeager**
*Caused by #307*

Convert from NetParameter to string back to NetParameter to avoid this error:

> TypeError: Parameter to MergeFrom() must be instance of same class:
expected caffe_pb2.NetParameter got caffe.proto.caffe_pb2.NetParameter.

/cc @ajtao

### CODE REVIEW

**Comment by lukeyeager** [comment]
To reproduce: try fine-tuning a model that was created with DIGITS before #307.

**Comment by lukeyeager** [comment]
@gheinrich can you try using this to upgrade some old jobs? I think it's correct but if something goes wrong with this sort of change it could potentially make someone lose all their old jobs.

**Comment by gheinrich** [comment]
I tried to upgrade old jobs (created prior to #307) and I could use them to classify images.

**Comment by lukeyeager** [comment]
Thanks for the review @gheinrich.

I've re-tested and still think this is the correct solution and a potentially useful fix. Plus, it will be a no-op unless people still have super old jobs lying around.

**Pull request merged**
