### PR TITLE
Address protobuf PicklingErrors on all platforms

### LINKED ISSUE #306: Address PicklingError for all OS's
*See #32 and [this thread](https://groups.google.com/d/msg/digits-users/LFq1OrxM-rU/oWgJp-2CCgAJ)*

People get `PicklingErrors` when trying to pickle protobuf objects. This happens on OSX, but also on Ubuntu 15.04 and even 14.04 in some cases. We should take the fix from 9824be9a7e56d1f375e5deac394527f56e73e99f and use it for all platforms.

### PR DESCRIPTION
**Pull request by lukeyeager**
Close #306

### CODE REVIEW

**Comment by lukeyeager** [comment]
> I've pulled your branch locally and it fixes the error on my Arch Linux environment.
https://groups.google.com/d/msg/digits-users/LFq1OrxM-rU/ytBktzCUAwAJ

Still waiting on some more feedback/testing before merging this.

/cc @assaad, @RudolphV, @stefmar, @trivedigaurav

**Comment by trivedigaurav** [comment]
I can confirm that I am no longer seeing pickling errors with this change.

**Comment by lukeyeager** [comment]
Awesome, thanks @trivedigaurav!

@gheinrich, any concerns with merging this?

**Comment by gheinrich** [comment]
That looks good to me.

**Pull request merged**
