### PR TITLE
Use dictionary for dataset/model options

### PR DESCRIPTION
**Pull request by gheinrich**
This will make it easier to add dataset/model types

### CODE REVIEW

**Comment by lukeyeager** [comment]
Fine with me. But you probably want to switch to using an [OrderedDict](https://docs.python.org/2/library/collections.html#collections.OrderedDict) to preserve the order when displayed on the page.

**Comment by gheinrich** [comment]
Yes, possibly. In my preliminary work on data extensions [there](https://github.com/gheinrich/DIGITS/blob/dev/data-extensions/digits/views.py#L65-L76) I am adding items to the dictionary by iterating through the list of supported extensions. I am not sure what's best between the default (alphanumeric) ordering of a dictionary or the chronological order of an `OrderedDict`. Any preference? 

For consistency perhaps the values of `new_dataset_options` and `new_model_options` should also be (ordered) dictionaries? With the `id` field being the key.

**Comment by lukeyeager** [comment]
> In my preliminary work on data extensions there I am adding items to the dictionary by iterating through the list of supported extensions.

Cool! I like it.

> I am not sure what's best between the default (alphanumeric) ordering of a dictionary or the chronological order of an OrderedDict. Any preference?

Well iterating through keys of a `dict` doesn't promise any particular order:
```py
>>> {'a':1,'b':2,'d':3,'c':4}.keys()
['a', 'c', 'b', 'd']
```
So either use an `OrderedDict` or iterate through `sorted(dict.keys())`. The latter might make more sense depending on how you implement `extensions.data.get_extensions()`.

> For consistency perhaps the values of new_dataset_options and new_model_options should also be (ordered) dictionaries? With the id field being the key.

Sure, yeah. I guess OrderedDicts are slightly easier to work with than lists of tuples.

**Comment by gheinrich** [comment]
Thanks for the feedback. I've changed the code to use only dictionaries. Since the sorting is a visualization preference this is done from the Jinja template.

**Pull request merged**
