### PR TITLE
Add # of learned parameters to weights vis

### PR DESCRIPTION
**Pull request by lukeyeager**
See #220. Also made some subtle UI changes.

### CODE REVIEW

**Comment by lukeyeager** [comment]
FYI, here are the number of parameters for each of the standard networks:

Network | Learned Parameters
------------ | -------------
LeNet | 431,080
AlexNet | 56,901,000
GoogLeNet | 13,378,280

**Comment by sudeepgaddam** [comment]
Where does this show up in tool exactly?? Before training, after entering network prototxt, Visualise network?

**Comment by lukeyeager** [comment]
You'll see it when you test an image on a trained model and check the box for "Show visualizations and statistics."

**Comment by lukeyeager** [comment]
Example of this in action (highlighting added):

parameter-count-example

**Pull request merged**
