### PR TITLE
Add gradient view extension and update regression tutorial

### PR DESCRIPTION
**Pull request by gheinrich**
Depends on #785

### CODE REVIEW

**Comment by lukeyeager** [comment]
I'm getting an error when trying to test an LMDB on a gradients model:
```
  File "/home/lyeager/digits/digits/model/images/generic/views.py", line 435, in infer_db
    summary_html=summary_html,
UnboundLocalError: local variable 'summary_html' referenced before assignment
```

**Comment by gheinrich** [comment]
> I'm getting an error when trying to test an LMDB

Only with Torch, right? I'm preparing a patch for this, thanks!

**Comment by lukeyeager** [comment]
> Only with Torch, right?

Nope, that was with Caffe

**Comment by lukeyeager** [comment]
Thanks for fixing that (unrelated) bug in https://github.com/NVIDIA/DIGITS/pull/791. This works great now!

**Pull request merged**
